name: Release a new version

permissions:
  id-token: write
  attestations: write
  contents: write

env:
  BINARY_PATH: target/release/github-secrets-observer

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update rust toolchain
        run: |
          rustup update
      - name: Build
        run: |
          cargo build --release
      - name: Generate Checksums
        run: |
          sha256sum ${{ env.BINARY_PATH }} > sha256sum.txt
          md5sum ${{ env.BINARY_PATH }} > md5sum.txt
      - name: Attest Build Provenance
        uses: actions/attest-build-provenance@v1
        with:
          subject-path: ${{ env.BINARY_PATH }}
      - name: Publish release
        uses: softprops/action-gh-release@de2c0eb89ae2a093876385947365aca7b0e5f844
        with:
          name: ${{ github.ref_name }}
          files: |
            ${{ env.BINARY_PATH }}
            sha256sum.txt
            md5sum.txt
            LICENSE
          token: ${{ secrets.GITHUB_TOKEN }}